# Generated by Django 4.0.4 on 2023-12-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='span',
            name='label',
            field=models.IntegerField(default=0),
        ),
    ]
