# Generated by Django 4.2.9 on 2024-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trace_app', '0002_span_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(default='', max_length=200)),
                ('task_status', models.CharField(default='', max_length=100)),
                ('task_progress', models.CharField(default='', max_length=100)),
                ('task_time', models.DateTimeField()),
                ('learning_rate', models.FloatField(default=0.0001)),
                ('batch_size', models.IntegerField(default=32)),
                ('epoch', models.IntegerField(default=15)),
                ('number_of_labels', models.IntegerField()),
            ],
        ),
    ]
