# Generated by Django 4.2.9 on 2024-04-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trace_app", "0004_alter_task_task_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="span", name="timestamp", field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_progress",
            field=models.CharField(default="25%", max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("Model training", "MODEL_TRAINING"),
                    ("Completed", "COMPLETED"),
                    ("Anomaly labeling", "ANOMALY_LABELING"),
                    ("Root Cause labeling", "ROOT_CAUSE_LABELING"),
                ],
                default="Model training",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
