# Generated by Django 4.2.9 on 2024-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trace_app", "0005_alter_span_timestamp_alter_task_task_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="span",
            name="timestamp",
            field=models.CharField(default="", max_length=100),
        ),
    ]
